name: "Unix TeX Live Setup"
description: "Installs TeX Live on Unix-based Systems"
runs:
  using: "composite"
  steps:
    - name: Install
      run: |
        curl -s -O -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
        unzip -q install-tl.zip
        rm install-tl.zip
        mv install-tl* install-tl
        install-tl/install-tl -profile ${{ github.action_path }}/texlive.profile
        rm -rf install-tl
      shell: bash
