name: Tests
env:
  cache-version: v5
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            CACHE_DIR: /tmp/texlive
            BIN_PATH: /tmp/texlive/bin/x86_64-linux
          - os: ubuntu-22.04
            CACHE_DIR: /tmp/texlive
            BIN_PATH: /tmp/texlive/bin/x86_64-linux
          - os: macos-11
            CACHE_DIR: /tmp/texlive
            BIN_PATH: /tmp/texlive/bin/universal-darwin
          - os: macos-12
            CACHE_DIR: /tmp/texlive
            BIN_PATH: /tmp/texlive/bin/universal-darwin
          - os: windows-2019
            CACHE_DIR: D:\texlive
            BIN_PATH: D:\texlive\bin\win32
          - os: windows-2022
            CACHE_DIR: D:\texlive
            BIN_PATH: D:\texlive\bin\win32
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache environments
        id: cache-env
        uses: actions/cache@v3
        with:
          path: ${{ matrix.CACHE_DIR }}
          key: ${{ env.cache-version }}-${{ matrix.os }}-env
          restore-keys: ${{ env.cache-version }}-${{ matrix.os }}-env
      - name: Install TeX Live (Windows)
        if: ${{ steps.cache-env.outputs.cache-hit != 'true' && runner.os == 'Windows' }}
        uses: ./.github/actions/texlive-windows
      - name: Install TeX Live (Unix)
        if: ${{ steps.cache-env.outputs.cache-hit != 'true' && runner.os != 'Windows' }}
        uses: ./.github/actions/texlive-unix
      - name: Set PATH
        run: echo "${{ matrix.BIN_PATH }}" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -U pandas matplotlib Pygments Jinja2
          tlmgr option -- autobackup 0
          tlmgr update --self
          tlmgr install pgfplots lualatex-math luacode listings
          tlmgr install fvextra catchfile xstring framed minted
          tlmgr remove pyluatex || true
      - name: Copy repository to LaTeX package folder
        run: |
          mkdir -p ~/texmf/tex/latex/pyluatex
          cp -r . ~/texmf/tex/latex/pyluatex/
        shell: bash
      - name: Run tests
        run: |
          cd test
          python3 run_tests.py
      - name: Run examples
        run: |
          cd example
          lualatex -shell-escape --interaction=nonstopmode data-visualization.tex
          lualatex -shell-escape --interaction=nonstopmode readme-example.tex
          lualatex -shell-escape --interaction=nonstopmode sessions.tex
          lualatex -shell-escape --interaction=nonstopmode matplotlib-external.tex
          lualatex -shell-escape --interaction=nonstopmode matplotlib-pgf.tex
          lualatex -shell-escape --interaction=nonstopmode typesetting-example.tex
          lualatex -shell-escape --interaction=nonstopmode typesetting-listings.tex
          lualatex -shell-escape --interaction=nonstopmode typesetting-minted.tex
          lualatex -shell-escape --interaction=nonstopmode readme-custom-env.tex
          lualatex -shell-escape --interaction=nonstopmode beamer.tex
          lualatex -shell-escape --interaction=nonstopmode repl.tex
